sonar.projectKey=sonar-with-jenkins
sonar.projectName=Sonar with Jenkins
sonar.projectVersion=1.0

# Source files
sonar.sources=.

# Encoding
sonar.sourceEncoding=UTF-8

# Optional: skip node_modules
sonar.exclusions=node_modules/**
